added 7-converter
Julia-Bo/JS_Purple pull request #4
Opened 2023-10-09 08:40 UTC by Julia-Bo

2023-11-01 20:35 UTC, Levitinn requested changes
логика ясна, но очень тяжело для восприятия. когда условий много, их тяжело читать. давай попробуем переделать это на более удобную, в данном случае, конструкцию? например switch case

2023-11-01 20:35 UTC, Levitinn commented on task_converter.js
> +    (originalCurrency === 'rub' && targetСurrency === 'usd') ?
скобки лишние. если их убрать, результат не изменится

2023-11-01 20:35 UTC, Levitinn commented on task_converter.js
> +    (originalCurrency === 'rub' && targetСurrency === 'usd') ?
п.с. как и в каждом следующем условии

2023-11-04 21:39 UTC, Julia-Bo commented
Принято, переделала)

2023-11-04 22:38 UTC, Levitinn approved these changes
хорошо)

2023-11-05 13:57 UTC, merged