8-crypto
Julia-Bo/JS_Purple pull request #5
Opened 2023-10-28 11:41 UTC by Julia-Bo

2023-10-28 11:51 UTC, Julia-Bo commented
Смущает, что так и не поняла как сделать так, чтобы работоспособность кода не зависела от количества символов в слове.
Как это сделать?

2023-11-01 20:37 UTC, Levitinn requested changes
твое решение привязано к конкретным индексам строки ( 
например code[2], code[3] \ code.splice(4, 3) и тд. можно попробовать кодировать слово по частям, например, по половинам. так можно будет решить эту проблему )

2023-11-04 21:38 UTC, Julia-Bo commented
спасибо. Изменения внесены)

2023-11-04 23:15 UTC, Levitinn requested changes
мне не очень нравится это решение. свитч кейс здесь явно лишние, ведь если в пароле не будет a\b\c  то это работать не будет. давай ты попробуешь сделать так, чтобы не привязываться к конкретным символам. Например, по позиции символа в слове, это ок, а по конкретному значению, не ок. мы же не можем предугадать какой пароль решит сделать юзер

2023-11-04 23:15 UTC, Levitinn commented on task_crypto.js
> +    wordArr = ([...secondPart,...firstPart]).join('')
зачем здесь (.....) круглые скобки? ниже такая же конструкция у тебя.

2023-11-05 13:55 UTC, Julia-Bo commented on task_crypto.js
> +    wordArr = ([...secondPart,...firstPart]).join('')
хотелось интересно запутать, но, согласна, при определенных символах код работал бы некорректно)
свитч уберу

2023-11-06 19:43 UTC, Levitinn approved these changes

2023-11-10 12:19 UTC, merged