11-data-array
Julia-Bo/JS_Purple pull request #8
Opened 2023-11-20 21:03 UTC by Julia-Bo

added 11-data-array

2023-12-04 08:47 UTC, Levitinn requested changes

2023-12-04 08:47 UTC, Levitinn commented on task_data_array.js
> +            return undefined;
если ничего не возвращать, мап по умолчанию вернет undefined

2023-12-04 08:47 UTC, Levitinn commented on task_data_array.js
> +            }
if (month <= 0 || month > 12) 
эти условия можно объединить. 
ниже с днями так же

2023-12-08 18:08 UTC, Julia-Bo commented on task_data_array.js
> +            return undefined;
согласна, можно было не писать, но казалось что без строчки смысл не закончен)

2023-12-08 18:26 UTC, Levitinn approved these changes

2023-12-16 11:15 UTC, merged